# Generated by Django 5.0.1 on 2024-01-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='quantidade_perguntas',
            field=models.IntegerField(),
        ),
    ]
